export { type TemplateData, processTemplatesFromPrefix, hasTemplatesWithPrefix } from "./utils";
export { processBaseTemplate } from "./base";
export { processFrontendTemplates } from "./frontend";
export { processBackendTemplates } from "./backend";
export { processDbTemplates } from "./database";
export { processApiTemplates } from "./api";
export { processConfigPackage, processEnvPackage } from "./packages";
export { processAuthTemplates } from "./auth";
export { processPaymentsTemplates } from "./payments";
export { processAddonTemplates } from "./addons";
export { processExampleTemplates } from "./examples";
export { processExtrasTemplates } from "./extras";
export { processDeployTemplates } from "./deploy";
